/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanLocalRouteImport } from './routes/scan-local'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsLocalRouteImport } from './routes/reports-local'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsLocalIdRouteImport } from './routes/reports-local.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedScansIdRouteImport } from './routes/_authenticated/scans.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLocalRoute = ScanLocalRouteImport.update({
  id: '/scan-local',
  path: '/scan-local',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLocalRoute = ReportsLocalRouteImport.update({
  id: '/reports-local',
  path: '/reports-local',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLocalIdRoute = ReportsLocalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsLocalRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansIdRoute = AuthenticatedScansIdRouteImport.update({
  id: '/scans/$id',
  path: '/scans/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/reports-local': typeof ReportsLocalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/scan-local': typeof ScanLocalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/scan': typeof AuthenticatedScanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/reports-local/$id': typeof ReportsLocalIdRoute
  '/scans/$id': typeof AuthenticatedScansIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/reports-local': typeof ReportsLocalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/scan-local': typeof ScanLocalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/scan': typeof AuthenticatedScanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/reports-local/$id': typeof ReportsLocalIdRoute
  '/scans/$id': typeof AuthenticatedScansIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/reports-local': typeof ReportsLocalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/scan-local': typeof ScanLocalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/reports-local/$id': typeof ReportsLocalIdRoute
  '/_authenticated/scans/$id': typeof AuthenticatedScansIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reports-local'
    | '/reset-password'
    | '/scan-local'
    | '/sitemap.xml'
    | '/history'
    | '/scan'
    | '/auth/callback'
    | '/reports-local/$id'
    | '/scans/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reports-local'
    | '/reset-password'
    | '/scan-local'
    | '/sitemap.xml'
    | '/history'
    | '/scan'
    | '/auth/callback'
    | '/reports-local/$id'
    | '/scans/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard'
    | '/reports-local'
    | '/reset-password'
    | '/scan-local'
    | '/sitemap.xml'
    | '/_authenticated/history'
    | '/_authenticated/scan'
    | '/auth/callback'
    | '/reports-local/$id'
    | '/_authenticated/scans/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ReportsLocalRoute: typeof ReportsLocalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanLocalRoute: typeof ScanLocalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-local': {
      id: '/scan-local'
      path: '/scan-local'
      fullPath: '/scan-local'
      preLoaderRoute: typeof ScanLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports-local': {
      id: '/reports-local'
      path: '/reports-local'
      fullPath: '/reports-local'
      preLoaderRoute: typeof ReportsLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports-local/$id': {
      id: '/reports-local/$id'
      path: '/$id'
      fullPath: '/reports-local/$id'
      preLoaderRoute: typeof ReportsLocalIdRouteImport
      parentRoute: typeof ReportsLocalRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans/$id': {
      id: '/_authenticated/scans/$id'
      path: '/scans/$id'
      fullPath: '/scans/$id'
      preLoaderRoute: typeof AuthenticatedScansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedScansIdRoute: typeof AuthenticatedScansIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedScansIdRoute: AuthenticatedScansIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ReportsLocalRouteChildren {
  ReportsLocalIdRoute: typeof ReportsLocalIdRoute
}

const ReportsLocalRouteChildren: ReportsLocalRouteChildren = {
  ReportsLocalIdRoute: ReportsLocalIdRoute,
}

const ReportsLocalRouteWithChildren = ReportsLocalRoute._addFileChildren(
  ReportsLocalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ReportsLocalRoute: ReportsLocalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanLocalRoute: ScanLocalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
